### ISSUE TITLE
Doesn't work with cider 0.11.0

### ISSUE THREAD

**Issue by smaant** [pjstadig/humane-test-output#10]
After running failing test in messages appears

```
error in process filter: nrepl-dict-get: Not a nREPL dict object: dict
error in process filter: Not a nREPL dict object: dict
```

And no results in test report:

```
Test Summary
com.me.app-test

Ran 37 tests, in 3 test functions
11 failures


Results


```

Some details here https://github.com/clojure-emacs/cider/issues/1546

**Comment by pjstadig** [comment]
I have not upgraded to cider 0.11.0 yet, but it would not surprise me. What humane-test-output does in pretty hacky, and has bad interactions with Cursive and other IDEs that attempt to provide better test output. That is why the recommended use is as a user plugin instead of a project plugin, and also why the `INHUMANE_TEST_OUTPUT` feature exists.

If you would like to look into it, and there is a way to make humane-test-output compatible with cider 0.11.0 in a way that won't break compatibility with older versions of cider, then I'd be glad to accept a patch. Otherwise, the best solution may just be to not use humane-test-output with cider 0.11.0.

**Comment by pjstadig** [comment]
cider (and other IDEs) produce more readable and useful output, so I don't recommend using humane-test-output with cider. I've updated the README to make this clearer. I think humane-test-output can still be useful at the CLI, but it was always a really hacky substitute for improved IDE output (which is better now).
