### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot write value of type class java.lang.Double

### ISSUE THREAD

**Issue by drewr** [pjstadig/humane-test-output#18]
As described in clojure-emacs/cider-nrepl#251, something's awry here interacting with nrepl.

**Comment by pjstadig** [comment]
I've commented on this issue before: https://github.com/clojure-emacs/cider-nrepl/pull/330#issuecomment-206453874 It is due to a change in how cider filters the keys in test report objects.

I think the options are: 1) stop using humane-test-output which isn't so bad since things have gotten better since I wrote it and it may not be necessary anymore, or 2) make a fix in cider's encoding/decoding.

**Comment by drewr** [comment]
Thanks @pjstadig, hadn't seen that other comment.

![](http://i0.kym-cdn.com/photos/images/newsfeed/000/201/508/221435NothingtodoHereGifMadethiscuzIwas2479d82822723.gif)
