### ISSUE TITLE
Intended behavior for records?

### ISSUE THREAD

**Issue by xpe** [pjstadig/humane-test-output#2]
I tried out human-test-output and found that it displays records as plain maps. Is this intended? I would rather have the output show the record explicitly.

**Comment by wiseman** [comment]
There seems to be a bug with records, too:  If I have `(is (= {:foo 1} (make-record))` where `make-record` returns a record that is essentially `{:foo 1}`, then the test fails but there is no output at all.

E.g., with humane-test-output:

```
FAIL in (at2-tests) (at2_test.clj:23)
construct pcmd
```

Without humane-test-output:

```
FAIL in (at2-tests) (at2_test.clj:23)
construct pcmd
expected: (= {:type "PCMD", :args [1 0 0 1056964608 0], :blocks? false, :options nil, :callback nil} (at2/build-command :pcmd {:up 0.5}))
  actual: (not (= {:args [1 0 0 1056964608 0], :type "PCMD", :options nil, :callback nil, :blocks? false} #com.lemondronor.turboshrimp.at2.AtCommand{:type "PCMD", :args [1 0 0 1056964608 0], :blocks? false, :options nil, :callback nil}))
```

**Comment by pjstadig** [comment]
Sorry for the late reply. For some reason I was not notified when this issue was created.

@xpe it appears that records are printing as plain maps because that is the way clojure.pprint/pprint prints them out.

@wiseman in your case a plain map and a record (even with the same keys and values) are not considered equal, but the clojure.data/diff function does consider them equal, because it doesn't bother to check if they are records. So the test fails, but the diff comes back empty.

So there are two separate issues here: clojure.pprint/pprint needs to learn about records, and clojure.data/diff needs to learn about records. Actually maybe three, because humane-test-output should fallback to printing out just the expected and actual values if the diff is empty.

The clojure.data/diff case seems pretty simple. There are a couple of protocols that can be extended. However, once that is done you'll get output like this:

``` clojure
AIL in (a-test) (core_test.clj:7)
FIXME, I fail.
expected: {:foo 1}
  actual: {:foo 1}
    diff: - {:foo 1}
          + {:foo 1}
```

Because pprint doesn't print the record with its type tag.

The pprint case is a bit more difficult, but after copying-and-pasting-and-modifying some code from clojure.pprint I'm able to get this:

``` clojure
FAIL in (a-test) (core_test.clj:7)
FIXME, I fail.
expected: {:foo 1}
  actual: #records_test.core.Foo{:foo 1}
    diff: - {:foo 1}
          + #records_test.core.Foo{:foo 1}
```

It's a bit hacky, and there's one little bit I'm a tad concerned about, because I had to remove a reference to a private var from clojure.pprint. I'm also not too keen on the diff being the entire contents of a map (which could be largeish). It would be better if it could say "this one has this type and that one has that type" as the only bit of information in the diff.

I'll try to push up a branch in a little bit, but I'd like to think on this one a bit to see if any cleaner alternatives come to mind. Either way, both of these issues are worth adding to the Clojure Jira (and then crossing your fingers).

**Comment by pjstadig** [comment]
Here's the branch https://github.com/pjstadig/humane-test-output/tree/records

**Comment by pjstadig** [comment]
0.7.0 has been released, and it includes this fix.
